"""Skug combot constants."""
CHARACTER_NAME_COLUMN = 'Character'
MOVE_NAME_COLUMN = 'Move Name'
HIT_NUMBER_COLUMN = 'Hit Number'
DAMAGE_COLUMN = 'Damage'
DAMAGE_SCALING_COLUMN = 'DamageScaling'
SCALED_DAMAGE_COLUMN = 'Scaled Damage'
UNDIZZY_COLUMN = 'Undizzy'
DAMAGE_SCALING_MIN = 0.2
DAMAGE_SCALING_MIN_ABOVE_1K = 0.275
DAMAGE_SCALING_FACTOR = 0.875
